# LAB 1: Matrix and Vector Computations in python
In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [1]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import sympy as sym

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [3]:
#type your code here:

# Scalar
s = np.array(5)

# Vector
v = np.array([5, -2, 4])  # Assuming 'r1' is a variable containing the value

# Matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Matrix B
B = np.array([[1, 2, 3],
              [4, 5, 6]])

# Matrix C
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [4]:
#type your code here:
print("type(s) = ", type(s))
print("type(v) = ", type(v))
print("type(A) = ", type(A))

type(s) =  <class 'numpy.ndarray'>
type(v) =  <class 'numpy.ndarray'>
type(A) =  <class 'numpy.ndarray'>


c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [5]:
#type your code here:
print("Shape of s:", s.shape)
print("Shape of v:", v.shape)
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)
print("Shape of C:", C.shape)

Shape of s: ()
Shape of v: (3,)
Shape of A: (3, 3)
Shape of B: (2, 3)
Shape of C: (3, 2)


d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [6]:
#type your code here:
print("Value at A[2, 1]:", A[2, 1])
A[2, 1] = 10
print("Updated matrix A:\n", A)

Value at A[2, 1]: 8
Updated matrix A:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [7]:
#type your code here:
second_column = A[:, 1]
print("Second column of A:\n", second_column)

Second column of A:
 [ 2  5 10]


f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [8]:
#type your code here:

eye_matrix = np.eye(4)
zeros_matrix_3x3 = np.zeros((3, 3))
zeros_vector_3x1 = np.zeros((3, 1))
zeros_matrix_3x5 = np.zeros((3, 5))
ones_matrix_2x3 = np.ones((2, 3))
diag_matrix = np.diag([4, 5, 6, 7])

print("Identity matrix:\n", eye_matrix)
print("Zeros matrix 3x3:\n", zeros_matrix_3x3)
print("Zeros vector 3x1:\n", zeros_vector_3x1)
print("Zeros matrix 3x5:\n", zeros_matrix_3x5)
print("Ones matrix 2x3:\n", ones_matrix_2x3)
print("Diagonal matrix:\n", diag_matrix)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Zeros matrix 3x3:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Zeros vector 3x1:
 [[0.]
 [0.]
 [0.]]
Zeros matrix 3x5:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones matrix 2x3:
 [[1. 1. 1.]
 [1. 1. 1.]]
Diagonal matrix:
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [9]:
#type your code here:
v1 = np.array([1, 2, 7, 4])
v2 = np.array([4, 3, 6, 8])

addition_result = v1 + v2
subtraction_result = v1 - v2
scaling_result_1 = 3 * v1
scaling_result_2 = v1 / 2

print("Addition:", addition_result)
print("Subtraction:", subtraction_result)
print("Scaling by 3:", scaling_result_1)
print("Scaling by 1/2:", scaling_result_2)

Addition: [ 5  5 13 12]
Subtraction: [-3 -1  1 -4]
Scaling by 3: [ 3  6 21 12]
Scaling by 1/2: [0.5 1.  3.5 2. ]


b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [10]:
#type your code here:

dot_product_1 = np.dot(v1, v2)

dot_product_2 = np.matmul(v1, v2)

dot_product_3 = v1 @ v2

print("Dot product using np.dot:", dot_product_1)
print("Dot product using np.matmul:", dot_product_2)
print("Dot product using @ operator:", dot_product_3)

Dot product using np.dot: 84
Dot product using np.matmul: 84
Dot product using @ operator: 84


c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [11]:
#type your code here:
import numpy as np

length_v1_norm = np.linalg.norm(v1)
length_v2_norm = np.linalg.norm(v2)

length_v1_dot = np.sqrt(np.dot(v1, v1))
length_v2_dot = np.sqrt(np.dot(v2, v2))

print("Length of v1 using np.linalg.norm:", length_v1_norm)
print("Length of v2 using np.linalg.norm:", length_v2_norm)

print("Length of v1 using dot product and np.sqrt:", length_v1_dot)
print("Length of v2 using dot product and np.sqrt:", length_v2_dot)

Length of v1 using np.linalg.norm: 8.366600265340756
Length of v2 using np.linalg.norm: 11.180339887498949
Length of v1 using dot product and np.sqrt: 8.366600265340756
Length of v2 using dot product and np.sqrt: 11.180339887498949


d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [11]:
#type your code here:
u = np.array([3, 2, -1, 4])
v = np.array([1, -1, 1, 0])

dot_product = np.dot(u, v)

print("Dot product:", dot_product)

Dot product: 0


# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

In [13]:
#type your code here:
u = np.array([2, 7, 2])
v = np.array([8, 4, 4])
A = np.array([[7, 3, 5],
              [4, 6, 2]])
B = np.array([[0, 6, 4],
              [2, 3, 0]])

A_plus_B = A + B
B_plus_A = B + A
three_A = 3 * A
six_B = 6 * B
two_times_three_B = 2 * (3 * B)
six_A_plus_fifteen_B = 6 * A + 15 * B
three_times_two_A_plus_five_B = 3 * (2 * A + 5 * B)
transpose_of_transpose_of_three_A = (3 * A.T).T

print("A + B:\n", A_plus_B)
print("B + A:\n", B_plus_A)
print("3A:\n", three_A)
print("6B:\n", six_B)
print("2(3B):\n", two_times_three_B)
print("6A + 15B:\n", six_A_plus_fifteen_B)
print("3(2A + 5B):\n", three_times_two_A_plus_five_B)
print("(3A^T)^T:\n", transpose_of_transpose_of_three_A)

A + B:
 [[7 9 9]
 [6 9 2]]
B + A:
 [[7 9 9]
 [6 9 2]]
3A:
 [[21  9 15]
 [12 18  6]]
6B:
 [[ 0 36 24]
 [12 18  0]]
2(3B):
 [[ 0 36 24]
 [12 18  0]]
6A + 15B:
 [[ 42 108  90]
 [ 54  81  12]]
3(2A + 5B):
 [[ 42 108  90]
 [ 54  81  12]]
(3A^T)^T:
 [[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [14]:
#type your code here:
u = np.array([2, 7, 2])
v = np.array([8, 4, 4])
A = np.array([[7, 3, 5],
              [4, 6, 2]])
B = np.array([[0, 6, 4],
              [2, 3, 0]])

Au = A @ u
Av = A @ v
Bu = B @ u

Au_plus_Av = Au + Av
A_times_u_plus_v = A @ (u + v)
A_plus_B_times_u = (A + B) @ u
Au_plus_Bu = Au + Bu
A_times_three_u = A @ (3 * u)
three_A_times_u = 3 * (A @ u)

print("Au + Av:\n", Au_plus_Av)
print("A(u + v):\n", A_times_u_plus_v)
print("(A + B)u:\n", A_plus_B_times_u)
print("Au + Bu:\n", Au_plus_Bu)
print("A(3u):\n", A_times_three_u)
print("3A(u):\n", three_A_times_u)

Au + Av:
 [133 118]
A(u + v):
 [133 118]
(A + B)u:
 [95 79]
Au + Bu:
 [95 79]
A(3u):
 [135 162]
3A(u):
 [135 162]
